#include <assert.h>
#include <emscripten.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int d(int max) {
  return rand()%max;
}

// These three lines are part of the "C calls JavaScript" bindings.
extern void new_sprite(int key, int x, int y, int which, int layer);
extern void set_sprite_position(int key, int x, int y, int flipped);
extern void set_sprite_tint(int key, int fraction);
extern void set_sprite_rotation(int key, float rotation);
extern void free_sprite(int key);
extern void print_debug(char* to_print);
extern void set_count(int tier, int inventory);
extern void set_muted(int new_muted);

// These three lines are part of the "Ceu invokes C" bindings.
#define ceu_out_emit_NEW_SPRITE(X) new_sprite(X->_1, X->_2, X->_3, X->_4, X->_5)
#define ceu_out_emit_SET_SPRITE_POSITION(X) set_sprite_position(X->_1, X->_2, X->_3, X->_4)
#define ceu_out_emit_SET_SPRITE_TINT(X) set_sprite_tint(X->_1, X->_2)
#define ceu_out_emit_SET_SPRITE_ROTATION(X) set_sprite_rotation(X->_1, X->_2)
#define ceu_out_emit_FREE_SPRITE(X) free_sprite(X->_1)
#define ceu_out_emit_SET_COUNT(X) set_count(X->_1, X->_2)
#define ceu_out_emit_PRINT_DEBUG(X) print_debug(X->_1);
#define ceu_out_emit_SET_MUTED(X) set_muted(X->_1)

#define ceu_out_assert(X) assert(X)
#define ceu_out_log(X) printf("%s\n", X)

typedef char* charptr;

// This is the C code generated by the Ceu compiler
#include "_ceu_app.c"

static byte CEU_DATA[sizeof(CEU_Main)];
static tceu_app app;

// These functions are exported to javascript by the emcc command line
// The bodies of these functions are the "C invokes Ceu" bindings.
void key_down(int which) {
  tceu__int payload = { which };
  ceu_sys_go( &app, CEU_IN_KEY_DOWN, &payload );
}

void key_up(int which) {
  tceu__int payload = { which };
  ceu_sys_go( &app, CEU_IN_KEY_UP, &payload );
}

void mouse_down(int x, int y) {
  tceu__int__int payload = { x, y };
  ceu_sys_go( &app, CEU_IN_MOUSE_DOWN, &payload );
}

void mouse_up(int x, int y) {
  tceu__int__int payload = { x, y };
  ceu_sys_go( &app, CEU_IN_MOUSE_UP, &payload );
}

void mouse_over(int x, int y) {
  tceu__int__int payload = { x, y };
  ceu_sys_go( &app, CEU_IN_MOUSE_OVER, &payload );
}

void mouse_out() {
  ceu_sys_go( &app, CEU_IN_MOUSE_OUT, NULL );
}

void mouse_move(int x, int y) {
  tceu__int__int payload = { x, y };
  ceu_sys_go( &app, CEU_IN_MOUSE_MOVE, &payload );
}

void update() {
  ceu_sys_go( &app, CEU_IN_UPDATE, NULL );
}

void begin() {
  memset(CEU_DATA, 0, sizeof(CEU_Main));
  app.data = (tceu_org*) &CEU_DATA;
  app.init = &ceu_app_init;
  app.init(&app);
}

