#include <assert.h>
#include <stdio.h>
#include <emscripten.h>

// These three lines are part of the "C calls JavaScript" bindings.
extern void new_bunny(int key, int x, int y);
extern void spin_bunny(int key);
extern void set_bunny_position(int key, int x, int y);
extern void free_bunny(int key);

// These three lines are part of the "Ceu invokes C" bindings.
#define ceu_out_emit_NEW_BUNNY(X) new_bunny(X->_1, X->_2, X->_3)
#define ceu_out_emit_SPIN_BUNNY(X) spin_bunny(X->_1)
#define ceu_out_emit_SET_BUNNY_POSITION(X) set_bunny_position(X->_1, X->_2, X->_3)
#define ceu_out_emit_FREE_BUNNY(X) free_bunny(X->_1)

#define ceu_out_assert(X) assert(X)
#define ceu_out_log(X) printf("%s\n", X)

// This is the C code generated by the Ceu compiler
#include "_ceu_app.c"

static byte CEU_DATA[sizeof(CEU_Main)];
static tceu_app app;

// These functions are exported to javascript by the emcc command line
// The bodies of these functions are the "C invokes Ceu" bindings.
void up_key_down() {
  ceu_sys_go( &app, CEU_IN_UP_KEY_DOWN, NULL );
}

void left_key_down() {
  ceu_sys_go( &app, CEU_IN_LEFT_KEY_DOWN, NULL );
}

void right_key_down() {
  ceu_sys_go( &app, CEU_IN_RIGHT_KEY_DOWN, NULL );
}

void up_key_up() {
  ceu_sys_go( &app, CEU_IN_UP_KEY_UP, NULL );
}

void left_key_up() {
  ceu_sys_go( &app, CEU_IN_LEFT_KEY_UP, NULL );
}

void right_key_up() {
  ceu_sys_go( &app, CEU_IN_RIGHT_KEY_UP, NULL );
}

void update() {
  ceu_sys_go( &app, CEU_IN_UPDATE, NULL );
}

void begin() {
  memset(CEU_DATA, 0, sizeof(CEU_Main));
  app.data = (tceu_org*) &CEU_DATA;
  app.init = &ceu_app_init;
  app.init(&app);
}

