#include <assert.h>
#include <math.h>
#include "table.h"
#include "SDL.h"
#include <stdio.h>

int cmpint(const void *x, const void *y) {
  if (**(int **)x < **(int **)y) {
    return -1;
  } else if (**(int **)x > **(int **)y) {
    return +1;
  } else {
    return 0;
  }
}

int intcmp(const void *x, const void *y) {
	return cmpint(&x, &y);
}

unsigned inthash(const void *x) {
	return *(int *)x;
}

int d(int max) {
  return rand()%max;
}

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 900

static void* sprites;

struct Sprite {
  int key;
  int x;
  int y;
  int which;
  int color;
  // TODO: int layer;
};


void new_sprite(int key, int x, int y, int which, int layer) {
  printf("new sprite: %d %d %d %d %d\n", key, x, y, which, layer);
  struct Sprite* new_sprite = malloc(sizeof(struct Sprite));
  new_sprite->key = key;
  new_sprite->x = x;
  new_sprite->y = y;
  new_sprite->which = which;
  new_sprite->color = 0xffffff;
  // TODO: layer
  Table_put(sprites, &(new_sprite->key), new_sprite);
}

void set_sprite_position(int key, int x, int y, int flipped) {
  struct Sprite* it = Table_get(sprites, &key);
  it->x = x;
  it->y = y;
  // TODO: flipped
}
//extern void set_sprite_tint(int key, int fraction);
//extern void set_sprite_rotation(int key, float rotation);

void free_sprite(int key) {
  printf("free sprite: %d\n", key);
  free(Table_remove(sprites, &key));
}

void set_count(int which, int new_value) {
  printf("You now have %d tier %d seeds.\n", new_value, which);
}

void print_debug(char* to_print) {
  printf("DEBUG: %s\n", to_print);
}

void set_muted(int new_muted) {
  if (new_muted) {
    printf("imagine we are now muted\n");
  } else {
    printf("imagine jungle sounds\n");
  }
}

// These three lines are part of the "Ceu invokes C" bindings.
#define ceu_out_emit_NEW_SPRITE(X) new_sprite(X->_1, X->_2, X->_3, X->_4, X->_5)
#define ceu_out_emit_SET_SPRITE_POSITION(X) set_sprite_position(X->_1, X->_2, X->_3, X->_4)
#define ceu_out_emit_SET_SPRITE_TINT(X) //set_sprite_tint(X->_1, X->_2)
#define ceu_out_emit_SET_SPRITE_ROTATION(X) //set_sprite_rotation(X->_1, X->_2)
#define ceu_out_emit_FREE_SPRITE(X) free_sprite(X->_1)
#define ceu_out_emit_SET_COUNT(X) set_count(X->_1, X->_2)
#define ceu_out_emit_PRINT_DEBUG(X) print_debug(X->_1)
#define ceu_out_emit_SET_MUTED(X) set_muted(X->_1)

#define ceu_out_assert(v) ceu_sys_assert(v)
void ceu_sys_assert (int v) {
  assert(v);
}

#define ceu_out_log(m,s) ceu_sys_log(m,s)
void ceu_sys_log (int mode, long s) {
  switch (mode) {
  case 0:
    printf("%s", (char*)s);
    break;
  case 1:
    printf("%lX", s);
    break;
  case 2:
    printf("%ld", s);
    break;
  }
}

typedef char* charptr;

// This is the C code generated by the Ceu compiler
#include "_ceu_app.c"

extern void ceu_app_init (tceu_app* app);

byte CEU_DATA[sizeof(CEU_Main)];
tceu_app app;

#include <stdlib.h>
#include <math.h>
#include "SDL.h"

#define TRUE 1

SDL_Surface *screen;
int running = TRUE;

// static SDL_Surface* bg;

void draw_sprite(const void* key, void** valueptr, void* cl) {
  struct Sprite* to_draw = *valueptr;
  struct SDL_Rect rect;
  rect.x = to_draw->x;
  rect.y = to_draw->y;
  rect.w = 10;
  rect.h = 10;
  SDL_FillRect(screen, &rect, to_draw->color);
}

void render() {
  struct SDL_Rect rect;
  rect.x = 0;
  rect.y = 0;
  rect.w = SCREEN_WIDTH;
  rect.h = SCREEN_HEIGHT;
  SDL_FillRect(screen, &rect, 0x999999);

  Table_map(sprites, draw_sprite, NULL);
}


void mainloop() {
  // Render stuff
  render();
  
  SDL_Flip(screen);  
  
  // Poll for events, and handle the ones we care about.
  SDL_Event event;
  while (SDL_PollEvent(&event)) {
    switch (event.type) {
    case SDL_QUIT: exit(0); break;
    case SDL_MOUSEBUTTONDOWN: /* TODO */ break;
    case SDL_MOUSEBUTTONUP: /* TODO */ break;
    }
  }

  ceu_sys_go(&app, CEU_IN_UPDATE, NULL);

  SDL_Delay( 1000 / 60 );
}

// Entry point
int main(int argc, char *argv[]) {
  sprites = Table_new(20, intcmp, inthash);

  app.data = (tceu_org*) &CEU_DATA;
  app.init = &ceu_app_init;
  app.init(&app);

  // bg = IMG_Load("bg.png");

  SDL_Init(SDL_INIT_VIDEO);
  atexit(SDL_Quit);
  screen = SDL_SetVideoMode(SCREEN_WIDTH, SCREEN_HEIGHT, 32, SDL_SWSURFACE);  
  if ( screen == NULL ) {
    exit(1);
  }
  while (1) {
    mainloop();
  }
  return 0;
}

