#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

int d(int max) {
  return rand()%max;
}

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 900

struct callbacks {
  void (*new_sprite)(int, int, int, int, int);
  void (*free_sprite)(int);
  void (*set_sprite_position)(int, int, int, int);
  void (*set_sprite_tint)(int, int);
  void (*set_sprite_rotation)(int, float);
  void (*set_count)(int, int);
  void (*set_muted)(int);
};

static struct callbacks callbacks;

// These three lines are part of the "Ceu invokes C" bindings.
#define ceu_out_emit_NEW_SPRITE(X) callbacks.new_sprite(X->_1, X->_2, X->_3, X->_4, X->_5)
#define ceu_out_emit_FREE_SPRITE(X) callbacks.free_sprite(X->_1)
#define ceu_out_emit_SET_SPRITE_POSITION(X) callbacks.set_sprite_position(X->_1, X->_2, X->_3, X->_4)
#define ceu_out_emit_SET_SPRITE_TINT(X) callbacks.set_sprite_tint(X->_1, X->_2)
#define ceu_out_emit_SET_SPRITE_ROTATION(X) callbacks.set_sprite_rotation(X->_1, X->_2)
#define ceu_out_emit_SET_COUNT(X) callbacks.set_count(X->_1, X->_2)
#define ceu_out_emit_PRINT_DEBUG(X) 
#define ceu_out_emit_SET_MUTED(X) callbacks.set_muted(X->_1)

#define ceu_out_assert(v) ceu_sys_assert(v)
void ceu_sys_assert (int v) {
  assert(v);
}

#define ceu_out_log(m,s) ceu_sys_log(m,s)
void ceu_sys_log (int mode, long s) {
  switch (mode) {
  case 0:
    printf("%s", (char*)s);
    break;
  case 1:
    printf("%lX", s);
    break;
  case 2:
    printf("%ld", s);
    break;
  }
}

typedef char* charptr;

// This is the C code generated by the Ceu compiler
#include "_ceu_app.c"

extern void ceu_app_init (tceu_app* app);

byte CEU_DATA[sizeof(CEU_Main)];
tceu_app app;

void key_down(int which) {
  tceu__int payload = { which };
  ceu_sys_go( &app, CEU_IN_KEY_DOWN, &payload );
}

void key_up(int which) {
  tceu__int payload = { which };
  ceu_sys_go( &app, CEU_IN_KEY_UP, &payload );
}

void mouse_down(int x, int y) {
  tceu__int__int payload = { x, y };
  ceu_sys_go( &app, CEU_IN_MOUSE_DOWN, &payload );
}

void mouse_up(int x, int y) {
  tceu__int__int payload = { x, y };
  ceu_sys_go( &app, CEU_IN_MOUSE_UP, &payload );
}

void mouse_over(int x, int y) {
  tceu__int__int payload = { x, y };
  ceu_sys_go( &app, CEU_IN_MOUSE_OVER, &payload );
}

void mouse_out() {
  ceu_sys_go( &app, CEU_IN_MOUSE_OUT, NULL );
}

void mouse_move(int x, int y) {
  tceu__int__int payload = { x, y };
  ceu_sys_go( &app, CEU_IN_MOUSE_MOVE, &payload );
}

void update() {
  ceu_sys_go( &app, CEU_IN_UPDATE, NULL );
}

void begin(
           void (*new_sprite)(int, int, int, int, int),
           void (*free_sprite)(int),
           void (*set_sprite_position)(int, int, int, int),
           void (*set_sprite_tint)(int, int),
           void (*set_sprite_rotation)(int, float),
           void (*set_count)(int, int),
           void (*set_muted)(int)
) {
  callbacks.new_sprite = new_sprite;
  callbacks.free_sprite = free_sprite;
  callbacks.set_sprite_position = set_sprite_position;
  callbacks.set_sprite_tint = set_sprite_tint;
  callbacks.set_sprite_rotation = set_sprite_rotation;
  callbacks.set_count = set_count;
  callbacks.set_muted = set_muted;

  memset(CEU_DATA, 0, sizeof(CEU_Main));
  app.data = (tceu_org*) &CEU_DATA;
  app.init = &ceu_app_init;
  app.init(&app);
}


